log.info('Loading oreDict.gvy')

// ntm
ore_dict.add('ironAnvil', item('hbm:anvil_iron'))
ore_dict.add('ironAnvil', item('hbm:anvil_lead'))

ore_dict.add('foodCheese', item('hbm:cheese'))
ore_dict.add('foodCheese', item('hbm:cheese_quesadilla'))
ore_dict.add('foodCheese', item('hbm:canned_conserve:4'))

ore_dict.add('usedCloth', item('hbm:rag_damp'))
ore_dict.add('usedCloth', item('hbm:rag_piss'))

ore_dict.add('tierFiveAnvil', item('hbm:anvil_bismuth_bronze'))
ore_dict.add('tierFiveAnvil', item('hbm:anvil_saturnite'))
ore_dict.add('tierFiveAnvil', item('hbm:anvil_arsenic_bronze'))

ore_dict.add('flatStamp', item('hbm:stamp_stone_flat'))
ore_dict.add('flatStamp', item('hbm:stamp_iron_flat'))
ore_dict.add('flatStamp', item('hbm:stamp_steel_flat'))
ore_dict.add('flatStamp', item('hbm:stamp_titanium_flat'))
ore_dict.add('flatStamp', item('hbm:stamp_desh_flat'))
ore_dict.add('flatStamp', item('hbm:stamp_obsidian_flat'))

ore_dict.add('plateStamp', item('hbm:stamp_stone_plate'))
ore_dict.add('plateStamp', item('hbm:stamp_iron_plate'))
ore_dict.add('plateStamp', item('hbm:stamp_steel_plate'))
ore_dict.add('plateStamp', item('hbm:stamp_titanium_plate'))
ore_dict.add('plateStamp', item('hbm:stamp_desh_plate'))
ore_dict.add('plateStamp', item('hbm:stamp_obsidian_plate'))

ore_dict.add('wireStamp', item('hbm:stamp_stone_wire'))
ore_dict.add('wireStamp', item('hbm:stamp_iron_wire'))
ore_dict.add('wireStamp', item('hbm:stamp_steel_wire'))
ore_dict.add('wireStamp', item('hbm:stamp_titanium_wire'))
ore_dict.add('wireStamp', item('hbm:stamp_desh_wire'))
ore_dict.add('wireStamp', item('hbm:stamp_obsidian_wire'))

ore_dict.add('titaniumArmor', item('hbm:titanium_helmet'))
ore_dict.add('titaniumArmor', item('hbm:titanium_plate'))
ore_dict.add('titaniumArmor', item('hbm:titanium_legs'))
ore_dict.add('titaniumArmor', item('hbm:titanium_boots'))

ore_dict.add('titaniumTools', item('hbm:titanium_pickaxe'))
ore_dict.add('titaniumTools', item('hbm:titanium_sword'))
ore_dict.add('titaniumTools', item('hbm:titanium_axe'))
ore_dict.add('titaniumTools', item('hbm:titanium_shovel'))
ore_dict.add('titaniumTools', item('hbm:titanium_hoe'))

ore_dict.add("anyHeatBox", item('hbm:heater_oven'))
ore_dict.add("anyHeatBox", item('hbm:heater_oilburner'))
ore_dict.add("anyHeatBox", item('hbm:heater_firebox'))

ore_dict.remove("itemSilicon", item('refinedstorage:silicon'))

oreDict.add('batteryAnySelfCharging', item('hbm:battery_sc'))
oreDict.add('batteryAnySelfCharging', item('hbm:battery_sc:1'))
oreDict.add('batteryAnySelfCharging', item('hbm:battery_sc:2'))
oreDict.add('batteryAnySelfCharging', item('hbm:battery_sc:3'))
oreDict.add('batteryAnySelfCharging', item('hbm:battery_sc:4'))
oreDict.add('batteryAnySelfCharging', item('hbm:battery_sc:5'))
oreDict.add('batteryAnySelfCharging', item('hbm:battery_sc:6'))
oreDict.add('batteryAnySelfCharging', item('hbm:battery_sc:7'))
oreDict.add('batteryAnySelfCharging', item('hbm:battery_sc:8'))
oreDict.add('batteryAnySelfCharging', item('hbm:battery_sc:9'))

oreDict.add('bedrockOreWashed', item('hbm:bedrock_ore_new:32'))
oreDict.add('bedrockOreWashed', item('hbm:bedrock_ore_new:33'))
oreDict.add('bedrockOreWashed', item('hbm:bedrock_ore_new:34'))
oreDict.add('bedrockOreWashed', item('hbm:bedrock_ore_new:35'))
oreDict.add('bedrockOreWashed', item('hbm:bedrock_ore_new:36'))
oreDict.add('bedrockOreWashed', item('hbm:bedrock_ore_new:37'))

oreDict.add('bedrockOrePrimaryFraction', item('hbm:bedrock_ore_new:48'))
oreDict.add('bedrockOrePrimaryFraction', item('hbm:bedrock_ore_new:49'))
oreDict.add('bedrockOrePrimaryFraction', item('hbm:bedrock_ore_new:50'))
oreDict.add('bedrockOrePrimaryFraction', item('hbm:bedrock_ore_new:51'))
oreDict.add('bedrockOrePrimaryFraction', item('hbm:bedrock_ore_new:52'))
oreDict.add('bedrockOrePrimaryFraction', item('hbm:bedrock_ore_new:53'))

oreDict.add('bedrockOreRoastedPrimaryFraction', item('hbm:bedrock_ore_new:64'))
oreDict.add('bedrockOreRoastedPrimaryFraction', item('hbm:bedrock_ore_new:65'))
oreDict.add('bedrockOreRoastedPrimaryFraction', item('hbm:bedrock_ore_new:66'))
oreDict.add('bedrockOreRoastedPrimaryFraction', item('hbm:bedrock_ore_new:67'))
oreDict.add('bedrockOreRoastedPrimaryFraction', item('hbm:bedrock_ore_new:68'))
oreDict.add('bedrockOreRoastedPrimaryFraction', item('hbm:bedrock_ore_new:69'))

oreDict.add('bedrockOreSulfuricPrimaryFraction', item('hbm:bedrock_ore_new:80'))
oreDict.add('bedrockOreSulfuricPrimaryFraction', item('hbm:bedrock_ore_new:81'))
oreDict.add('bedrockOreSulfuricPrimaryFraction', item('hbm:bedrock_ore_new:82'))
oreDict.add('bedrockOreSulfuricPrimaryFraction', item('hbm:bedrock_ore_new:83'))
oreDict.add('bedrockOreSulfuricPrimaryFraction', item('hbm:bedrock_ore_new:84'))
oreDict.add('bedrockOreSulfuricPrimaryFraction', item('hbm:bedrock_ore_new:85'))

oreDict.add('bedrockOreDissolvedPrimaryFraction', item('hbm:bedrock_ore_new:112'))
oreDict.add('bedrockOreDissolvedPrimaryFraction', item('hbm:bedrock_ore_new:113'))
oreDict.add('bedrockOreDissolvedPrimaryFraction', item('hbm:bedrock_ore_new:114'))
oreDict.add('bedrockOreDissolvedPrimaryFraction', item('hbm:bedrock_ore_new:115'))
oreDict.add('bedrockOreDissolvedPrimaryFraction', item('hbm:bedrock_ore_new:116'))
oreDict.add('bedrockOreDissolvedPrimaryFraction', item('hbm:bedrock_ore_new:117'))

oreDict.add('bedrockOreCleanedPrimaryFraction', item('hbm:bedrock_ore_new:144'))
oreDict.add('bedrockOreCleanedPrimaryFraction', item('hbm:bedrock_ore_new:145'))
oreDict.add('bedrockOreCleanedPrimaryFraction', item('hbm:bedrock_ore_new:146'))
oreDict.add('bedrockOreCleanedPrimaryFraction', item('hbm:bedrock_ore_new:147'))
oreDict.add('bedrockOreCleanedPrimaryFraction', item('hbm:bedrock_ore_new:148'))
oreDict.add('bedrockOreCleanedPrimaryFraction', item('hbm:bedrock_ore_new:149'))

oreDict.add('bedrockOreHigherWeightPrimaryFraction', item('hbm:bedrock_ore_new:176'))
oreDict.add('bedrockOreHigherWeightPrimaryFraction', item('hbm:bedrock_ore_new:177'))
oreDict.add('bedrockOreHigherWeightPrimaryFraction', item('hbm:bedrock_ore_new:178'))
oreDict.add('bedrockOreHigherWeightPrimaryFraction', item('hbm:bedrock_ore_new:179'))
oreDict.add('bedrockOreHigherWeightPrimaryFraction', item('hbm:bedrock_ore_new:180'))
oreDict.add('bedrockOreHigherWeightPrimaryFraction', item('hbm:bedrock_ore_new:181'))

oreDict.add('bedrockOreLowerWeightPrimaryFraction', item('hbm:bedrock_ore_new:192'))
oreDict.add('bedrockOreLowerWeightPrimaryFraction', item('hbm:bedrock_ore_new:193'))
oreDict.add('bedrockOreLowerWeightPrimaryFraction', item('hbm:bedrock_ore_new:194'))
oreDict.add('bedrockOreLowerWeightPrimaryFraction', item('hbm:bedrock_ore_new:195'))
oreDict.add('bedrockOreLowerWeightPrimaryFraction', item('hbm:bedrock_ore_new:196'))
oreDict.add('bedrockOreLowerWeightPrimaryFraction', item('hbm:bedrock_ore_new:197'))

oreDict.add('bedrockOreSeparated', item('hbm:bedrock_ore_new:96'))
oreDict.add('bedrockOreSeparated', item('hbm:bedrock_ore_new:97'))
oreDict.add('bedrockOreSeparated', item('hbm:bedrock_ore_new:98'))
oreDict.add('bedrockOreSeparated', item('hbm:bedrock_ore_new:99'))
oreDict.add('bedrockOreSeparated', item('hbm:bedrock_ore_new:100'))
oreDict.add('bedrockOreSeparated', item('hbm:bedrock_ore_new:101'))

oreDict.add('bedrockOreSeparated', item('hbm:bedrock_ore_new:128'))
oreDict.add('bedrockOreSeparated', item('hbm:bedrock_ore_new:129'))
oreDict.add('bedrockOreSeparated', item('hbm:bedrock_ore_new:130'))
oreDict.add('bedrockOreSeparated', item('hbm:bedrock_ore_new:131'))
oreDict.add('bedrockOreSeparated', item('hbm:bedrock_ore_new:132'))
oreDict.add('bedrockOreSeparated', item('hbm:bedrock_ore_new:133'))

oreDict.add('bedrockOreSeparated', item('hbm:bedrock_ore_new:160'))
oreDict.add('bedrockOreSeparated', item('hbm:bedrock_ore_new:161'))
oreDict.add('bedrockOreSeparated', item('hbm:bedrock_ore_new:162'))
oreDict.add('bedrockOreSeparated', item('hbm:bedrock_ore_new:163'))
oreDict.add('bedrockOreSeparated', item('hbm:bedrock_ore_new:164'))
oreDict.add('bedrockOreSeparated', item('hbm:bedrock_ore_new:165'))

oreDict.add('bedrockOreSulfuric', item('hbm:bedrock_ore_new:224'))
oreDict.add('bedrockOreSulfuric', item('hbm:bedrock_ore_new:225'))
oreDict.add('bedrockOreSulfuric', item('hbm:bedrock_ore_new:226'))
oreDict.add('bedrockOreSulfuric', item('hbm:bedrock_ore_new:227'))
oreDict.add('bedrockOreSulfuric', item('hbm:bedrock_ore_new:228'))
oreDict.add('bedrockOreSulfuric', item('hbm:bedrock_ore_new:229'))

oreDict.add('bedrockOreDissolved', item('hbm:bedrock_ore_new:288'))
oreDict.add('bedrockOreDissolved', item('hbm:bedrock_ore_new:289'))
oreDict.add('bedrockOreDissolved', item('hbm:bedrock_ore_new:290'))
oreDict.add('bedrockOreDissolved', item('hbm:bedrock_ore_new:291'))
oreDict.add('bedrockOreDissolved', item('hbm:bedrock_ore_new:292'))
oreDict.add('bedrockOreDissolved', item('hbm:bedrock_ore_new:293'))
