log.info('Loading oreDict.gvy')

// ntm
ore_dict.add('ironAnvil', item('hbm:anvil_iron'))
ore_dict.add('ironAnvil', item('hbm:anvil_lead'))

oreDict.add('stoneResource', item('hbm:stone_resource:0'))
oreDict.add('stoneResource', item('hbm:stone_resource:1'))
oreDict.add('stoneResource', item('hbm:stone_resource:2'))
oreDict.add('stoneResource', item('hbm:stone_resource:3'))
oreDict.add('stoneResource', item('hbm:stone_resource:4'))
oreDict.add('stoneResource', item('hbm:stone_resource:5'))

oreDict.add('insert', item('hbm:insert_du'))
oreDict.add('insert', item('hbm:insert_esapi'))
oreDict.add('insert', item('hbm:insert_sapi'))
oreDict.add('insert', item('hbm:insert_xsapi'))
oreDict.add('insert', item('hbm:insert_kevlar'))
oreDict.add('insert', item('hbm:insert_polonium'))
oreDict.add('insert', item('hbm:insert_steel'))
oreDict.add('insert', item('hbm:insert_yharonite'))
oreDict.add('insert', item('hbm:insert_era'))

oreDict.add('coal', item('minecraft:coal'))
oreDict.add('coal', item('hbm:powder_coal'))

// calibers
oreDict.add('9mm', item('hbm:ammo_standard:20'))
oreDict.add('9mm', item('hbm:ammo_standard:21'))
oreDict.add('9mm', item('hbm:ammo_standard:22'))
oreDict.add('9mm', item('hbm:ammo_standard:23'))

oreDict.add('.22 LR', item('hbm:ammo_standard:16'))
oreDict.add('.22 LR', item('hbm:ammo_standard:17'))
oreDict.add('.22 LR', item('hbm:ammo_standard:18'))
oreDict.add('.22 LR', item('hbm:ammo_standard:19'))

oreDict.add('.45', item('hbm:ammo_standard:85'))
oreDict.add('.45', item('hbm:ammo_standard:86'))
oreDict.add('.45', item('hbm:ammo_standard:87'))
oreDict.add('.45', item('hbm:ammo_standard:88'))
oreDict.add('.45', item('hbm:ammo_standard:89'))

oreDict.add('.357', item('hbm:ammo_standard:4'))
oreDict.add('.357', item('hbm:ammo_standard:5'))
oreDict.add('.357', item('hbm:ammo_standard:6'))
oreDict.add('.357', item('hbm:ammo_standard:7'))
oreDict.add('.357', item('hbm:ammo_standard:8'))
oreDict.add('.357', item('hbm:ammo_standard:9'))

oreDict.add('.44', item('hbm:ammo_standard:10'))
oreDict.add('.44', item('hbm:ammo_standard:11'))
oreDict.add('.44', item('hbm:ammo_standard:12'))
oreDict.add('.44', item('hbm:ammo_standard:13'))
oreDict.add('.44', item('hbm:ammo_standard:14'))
oreDict.add('.44', item('hbm:ammo_standard:15'))

oreDict.add('5.56mm', item('hbm:ammo_standard:24'))
oreDict.add('5.56mm', item('hbm:ammo_standard:25'))
oreDict.add('5.56mm', item('hbm:ammo_standard:26'))
oreDict.add('5.56mm', item('hbm:ammo_standard:27'))

oreDict.add('7.62mm', item('hbm:ammo_standard:28'))
oreDict.add('7.62mm', item('hbm:ammo_standard:29'))
oreDict.add('7.62mm', item('hbm:ammo_standard:30'))
oreDict.add('7.62mm', item('hbm:ammo_standard:31'))
oreDict.add('7.62mm', item('hbm:ammo_standard:32'))
oreDict.add('7.62mm', item('hbm:ammo_standard:82'))

oreDict.add('.50 BMG', item('hbm:ammo_standard:33'))
oreDict.add('.50 BMG', item('hbm:ammo_standard:34'))
oreDict.add('.50 BMG', item('hbm:ammo_standard:35'))
oreDict.add('.50 BMG', item('hbm:ammo_standard:36'))
oreDict.add('.50 BMG', item('hbm:ammo_standard:37'))
oreDict.add('.50 BMG', item('hbm:ammo_standard:83'))
oreDict.add('.50 BMG', item('hbm:ammo_standard:94'))

// goofy how it isnt included by default
oreDict.add('blockSlag', item('hbm:block_slag:1'))

oreDict.add('Tungsten', item('hbm:powder_tungsten'))

ore_dict.add('foodCheese', item('hbm:cheese'))
ore_dict.add('foodCheese', item('hbm:cheese_quesadilla'))
ore_dict.add('foodCheese', item('hbm:canned_conserve:4'))

ore_dict.add('usedCloth', item('hbm:rag_damp'))
ore_dict.add('usedCloth', item('hbm:rag_piss'))

ore_dict.add('tierFiveAnvil', item('hbm:anvil_bismuth_bronze'))
ore_dict.add('tierFiveAnvil', item('hbm:anvil_saturnite'))
ore_dict.add('tierFiveAnvil', item('hbm:anvil_arsenic_bronze'))

ore_dict.add('flatStamp', item('hbm:stamp_stone_flat'))
ore_dict.add('flatStamp', item('hbm:stamp_iron_flat'))
ore_dict.add('flatStamp', item('hbm:stamp_steel_flat'))
ore_dict.add('flatStamp', item('hbm:stamp_titanium_flat'))
ore_dict.add('flatStamp', item('hbm:stamp_desh_flat'))
ore_dict.add('flatStamp', item('hbm:stamp_obsidian_flat'))

ore_dict.add('plateStamp', item('hbm:stamp_stone_plate'))
ore_dict.add('plateStamp', item('hbm:stamp_iron_plate'))
ore_dict.add('plateStamp', item('hbm:stamp_steel_plate'))
ore_dict.add('plateStamp', item('hbm:stamp_titanium_plate'))
ore_dict.add('plateStamp', item('hbm:stamp_desh_plate'))
ore_dict.add('plateStamp', item('hbm:stamp_obsidian_plate'))

ore_dict.add('wireStamp', item('hbm:stamp_stone_wire'))
ore_dict.add('wireStamp', item('hbm:stamp_iron_wire'))
ore_dict.add('wireStamp', item('hbm:stamp_steel_wire'))
ore_dict.add('wireStamp', item('hbm:stamp_titanium_wire'))
ore_dict.add('wireStamp', item('hbm:stamp_desh_wire'))
ore_dict.add('wireStamp', item('hbm:stamp_obsidian_wire'))

ore_dict.add('titaniumArmor', item('hbm:titanium_helmet'))
ore_dict.add('titaniumArmor', item('hbm:titanium_plate'))
ore_dict.add('titaniumArmor', item('hbm:titanium_legs'))
ore_dict.add('titaniumArmor', item('hbm:titanium_boots'))

ore_dict.add('titaniumTools', item('hbm:titanium_pickaxe'))
ore_dict.add('titaniumTools', item('hbm:titanium_sword'))
ore_dict.add('titaniumTools', item('hbm:titanium_axe'))
ore_dict.add('titaniumTools', item('hbm:titanium_shovel'))
ore_dict.add('titaniumTools', item('hbm:titanium_hoe'))

ore_dict.add("anyHeatBox", item('hbm:heater_oven'))
ore_dict.add("anyHeatBox", item('hbm:heater_oilburner'))
ore_dict.add("anyHeatBox", item('hbm:heater_firebox'))

ore_dict.remove("itemSilicon", item('refinedstorage:silicon'))

oreDict.add('batteryAnySelfCharging', item('hbm:battery_sc'))
oreDict.add('batteryAnySelfCharging', item('hbm:battery_sc:1'))
oreDict.add('batteryAnySelfCharging', item('hbm:battery_sc:2'))
oreDict.add('batteryAnySelfCharging', item('hbm:battery_sc:3'))
oreDict.add('batteryAnySelfCharging', item('hbm:battery_sc:4'))
oreDict.add('batteryAnySelfCharging', item('hbm:battery_sc:5'))
oreDict.add('batteryAnySelfCharging', item('hbm:battery_sc:6'))
oreDict.add('batteryAnySelfCharging', item('hbm:battery_sc:7'))
oreDict.add('batteryAnySelfCharging', item('hbm:battery_sc:8'))
oreDict.add('batteryAnySelfCharging', item('hbm:battery_sc:9'))

oreDict.add('bedrockOreFullWashed', item('hbm:bedrock_ore_new:32'))
oreDict.add('bedrockOreFullWashed', item('hbm:bedrock_ore_new:33'))
oreDict.add('bedrockOreFullWashed', item('hbm:bedrock_ore_new:34'))
oreDict.add('bedrockOreFullWashed', item('hbm:bedrock_ore_new:35'))
oreDict.add('bedrockOreFullWashed', item('hbm:bedrock_ore_new:36'))
oreDict.add('bedrockOreFullWashed', item('hbm:bedrock_ore_new:37'))

oreDict.add('bedrockOrePrimaryFraction', item('hbm:bedrock_ore_new:48'))
oreDict.add('bedrockOrePrimaryFraction', item('hbm:bedrock_ore_new:49'))
oreDict.add('bedrockOrePrimaryFraction', item('hbm:bedrock_ore_new:50'))
oreDict.add('bedrockOrePrimaryFraction', item('hbm:bedrock_ore_new:51'))
oreDict.add('bedrockOrePrimaryFraction', item('hbm:bedrock_ore_new:52'))
oreDict.add('bedrockOrePrimaryFraction', item('hbm:bedrock_ore_new:53'))

oreDict.add('bedrockOreRoastedPrimaryFraction', item('hbm:bedrock_ore_new:64'))
oreDict.add('bedrockOreRoastedPrimaryFraction', item('hbm:bedrock_ore_new:65'))
oreDict.add('bedrockOreRoastedPrimaryFraction', item('hbm:bedrock_ore_new:66'))
oreDict.add('bedrockOreRoastedPrimaryFraction', item('hbm:bedrock_ore_new:67'))
oreDict.add('bedrockOreRoastedPrimaryFraction', item('hbm:bedrock_ore_new:68'))
oreDict.add('bedrockOreRoastedPrimaryFraction', item('hbm:bedrock_ore_new:69'))

oreDict.add('bedrockOreSulfuricPrimaryFraction', item('hbm:bedrock_ore_new:80'))
oreDict.add('bedrockOreSulfuricPrimaryFraction', item('hbm:bedrock_ore_new:81'))
oreDict.add('bedrockOreSulfuricPrimaryFraction', item('hbm:bedrock_ore_new:82'))
oreDict.add('bedrockOreSulfuricPrimaryFraction', item('hbm:bedrock_ore_new:83'))
oreDict.add('bedrockOreSulfuricPrimaryFraction', item('hbm:bedrock_ore_new:84'))
oreDict.add('bedrockOreSulfuricPrimaryFraction', item('hbm:bedrock_ore_new:85'))

oreDict.add('bedrockOreDissolvedPrimaryFraction', item('hbm:bedrock_ore_new:112'))
oreDict.add('bedrockOreDissolvedPrimaryFraction', item('hbm:bedrock_ore_new:113'))
oreDict.add('bedrockOreDissolvedPrimaryFraction', item('hbm:bedrock_ore_new:114'))
oreDict.add('bedrockOreDissolvedPrimaryFraction', item('hbm:bedrock_ore_new:115'))
oreDict.add('bedrockOreDissolvedPrimaryFraction', item('hbm:bedrock_ore_new:116'))
oreDict.add('bedrockOreDissolvedPrimaryFraction', item('hbm:bedrock_ore_new:117'))

oreDict.add('bedrockOreCleanedPrimaryFraction', item('hbm:bedrock_ore_new:144'))
oreDict.add('bedrockOreCleanedPrimaryFraction', item('hbm:bedrock_ore_new:145'))
oreDict.add('bedrockOreCleanedPrimaryFraction', item('hbm:bedrock_ore_new:146'))
oreDict.add('bedrockOreCleanedPrimaryFraction', item('hbm:bedrock_ore_new:147'))
oreDict.add('bedrockOreCleanedPrimaryFraction', item('hbm:bedrock_ore_new:148'))
oreDict.add('bedrockOreCleanedPrimaryFraction', item('hbm:bedrock_ore_new:149'))

oreDict.add('bedrockOreHigherWeightPrimaryFraction', item('hbm:bedrock_ore_new:176'))
oreDict.add('bedrockOreHigherWeightPrimaryFraction', item('hbm:bedrock_ore_new:177'))
oreDict.add('bedrockOreHigherWeightPrimaryFraction', item('hbm:bedrock_ore_new:178'))
oreDict.add('bedrockOreHigherWeightPrimaryFraction', item('hbm:bedrock_ore_new:179'))
oreDict.add('bedrockOreHigherWeightPrimaryFraction', item('hbm:bedrock_ore_new:180'))
oreDict.add('bedrockOreHigherWeightPrimaryFraction', item('hbm:bedrock_ore_new:181'))

oreDict.add('bedrockOreLowerWeightPrimaryFraction', item('hbm:bedrock_ore_new:192'))
oreDict.add('bedrockOreLowerWeightPrimaryFraction', item('hbm:bedrock_ore_new:193'))
oreDict.add('bedrockOreLowerWeightPrimaryFraction', item('hbm:bedrock_ore_new:194'))
oreDict.add('bedrockOreLowerWeightPrimaryFraction', item('hbm:bedrock_ore_new:195'))
oreDict.add('bedrockOreLowerWeightPrimaryFraction', item('hbm:bedrock_ore_new:196'))
oreDict.add('bedrockOreLowerWeightPrimaryFraction', item('hbm:bedrock_ore_new:197'))

oreDict.add('bedrockOreSeparated', item('hbm:bedrock_ore_new:96'))
oreDict.add('bedrockOreSeparated', item('hbm:bedrock_ore_new:97'))
oreDict.add('bedrockOreSeparated', item('hbm:bedrock_ore_new:98'))
oreDict.add('bedrockOreSeparated', item('hbm:bedrock_ore_new:99'))
oreDict.add('bedrockOreSeparated', item('hbm:bedrock_ore_new:100'))
oreDict.add('bedrockOreSeparated', item('hbm:bedrock_ore_new:101'))

oreDict.add('bedrockOreSeparated', item('hbm:bedrock_ore_new:128'))
oreDict.add('bedrockOreSeparated', item('hbm:bedrock_ore_new:129'))
oreDict.add('bedrockOreSeparated', item('hbm:bedrock_ore_new:130'))
oreDict.add('bedrockOreSeparated', item('hbm:bedrock_ore_new:131'))
oreDict.add('bedrockOreSeparated', item('hbm:bedrock_ore_new:132'))
oreDict.add('bedrockOreSeparated', item('hbm:bedrock_ore_new:133'))

oreDict.add('bedrockOreSeparated', item('hbm:bedrock_ore_new:160'))
oreDict.add('bedrockOreSeparated', item('hbm:bedrock_ore_new:161'))
oreDict.add('bedrockOreSeparated', item('hbm:bedrock_ore_new:162'))
oreDict.add('bedrockOreSeparated', item('hbm:bedrock_ore_new:163'))
oreDict.add('bedrockOreSeparated', item('hbm:bedrock_ore_new:164'))
oreDict.add('bedrockOreSeparated', item('hbm:bedrock_ore_new:165'))

oreDict.add('bedrockOreSulfuric', item('hbm:bedrock_ore_new:224'))
oreDict.add('bedrockOreSulfuric', item('hbm:bedrock_ore_new:225'))
oreDict.add('bedrockOreSulfuric', item('hbm:bedrock_ore_new:226'))
oreDict.add('bedrockOreSulfuric', item('hbm:bedrock_ore_new:227'))
oreDict.add('bedrockOreSulfuric', item('hbm:bedrock_ore_new:228'))
oreDict.add('bedrockOreSulfuric', item('hbm:bedrock_ore_new:229'))

oreDict.add('bedrockOreDissolved', item('hbm:bedrock_ore_new:288'))
oreDict.add('bedrockOreDissolved', item('hbm:bedrock_ore_new:289'))
oreDict.add('bedrockOreDissolved', item('hbm:bedrock_ore_new:290'))
oreDict.add('bedrockOreDissolved', item('hbm:bedrock_ore_new:291'))
oreDict.add('bedrockOreDissolved', item('hbm:bedrock_ore_new:292'))
oreDict.add('bedrockOreDissolved', item('hbm:bedrock_ore_new:293'))

oreDict.add('bedrockOreCleaned', item('hbm:bedrock_ore_new:352'))
oreDict.add('bedrockOreCleaned', item('hbm:bedrock_ore_new:353'))
oreDict.add('bedrockOreCleaned', item('hbm:bedrock_ore_new:354'))
oreDict.add('bedrockOreCleaned', item('hbm:bedrock_ore_new:355'))
oreDict.add('bedrockOreCleaned', item('hbm:bedrock_ore_new:356'))
oreDict.add('bedrockOreCleaned', item('hbm:bedrock_ore_new:357'))
// Sulfuric
oreDict.add('bedrockOreSulfuricRoasted', item('hbm:bedrock_ore_new:240'))
oreDict.add('bedrockOreSulfuricRoasted', item('hbm:bedrock_ore_new:241'))
oreDict.add('bedrockOreSulfuricRoasted', item('hbm:bedrock_ore_new:242'))
oreDict.add('bedrockOreSulfuricRoasted', item('hbm:bedrock_ore_new:243'))
oreDict.add('bedrockOreSulfuricRoasted', item('hbm:bedrock_ore_new:244'))
oreDict.add('bedrockOreSulfuricRoasted', item('hbm:bedrock_ore_new:245'))

// Dissolved
oreDict.add('bedrockOreDissolvedRoasted', item('hbm:bedrock_ore_new:304'))
oreDict.add('bedrockOreDissolvedRoasted', item('hbm:bedrock_ore_new:305'))
oreDict.add('bedrockOreDissolvedRoasted', item('hbm:bedrock_ore_new:306'))
oreDict.add('bedrockOreDissolvedRoasted', item('hbm:bedrock_ore_new:307'))
oreDict.add('bedrockOreDissolvedRoasted', item('hbm:bedrock_ore_new:308'))
oreDict.add('bedrockOreDissolvedRoasted', item('hbm:bedrock_ore_new:309'))

// Cleaned
oreDict.add('bedrockOreCleanedRoasted', item('hbm:bedrock_ore_new:368'))
oreDict.add('bedrockOreCleanedRoasted', item('hbm:bedrock_ore_new:369'))
oreDict.add('bedrockOreCleanedRoasted', item('hbm:bedrock_ore_new:370'))
oreDict.add('bedrockOreCleanedRoasted', item('hbm:bedrock_ore_new:371'))
oreDict.add('bedrockOreCleanedRoasted', item('hbm:bedrock_ore_new:372'))
oreDict.add('bedrockOreCleanedRoasted', item('hbm:bedrock_ore_new:373'))

// Sulfuric
oreDict.add('bedrockOreSulfuricSeared', item('hbm:bedrock_ore_new:256'))
oreDict.add('bedrockOreSulfuricSeared', item('hbm:bedrock_ore_new:257'))
oreDict.add('bedrockOreSulfuricSeared', item('hbm:bedrock_ore_new:258'))
oreDict.add('bedrockOreSulfuricSeared', item('hbm:bedrock_ore_new:259'))
oreDict.add('bedrockOreSulfuricSeared', item('hbm:bedrock_ore_new:260'))
oreDict.add('bedrockOreSulfuricSeared', item('hbm:bedrock_ore_new:261'))

// Dissolved
oreDict.add('bedrockOreDissolvedSeared', item('hbm:bedrock_ore_new:320'))
oreDict.add('bedrockOreDissolvedSeared', item('hbm:bedrock_ore_new:321'))
oreDict.add('bedrockOreDissolvedSeared', item('hbm:bedrock_ore_new:322'))
oreDict.add('bedrockOreDissolvedSeared', item('hbm:bedrock_ore_new:323'))
oreDict.add('bedrockOreDissolvedSeared', item('hbm:bedrock_ore_new:324'))
oreDict.add('bedrockOreDissolvedSeared', item('hbm:bedrock_ore_new:325'))

// Cleaned
oreDict.add('bedrockOreCleanedSeared', item('hbm:bedrock_ore_new:384'))
oreDict.add('bedrockOreCleanedSeared', item('hbm:bedrock_ore_new:385'))
oreDict.add('bedrockOreCleanedSeared', item('hbm:bedrock_ore_new:386'))
oreDict.add('bedrockOreCleanedSeared', item('hbm:bedrock_ore_new:387'))
oreDict.add('bedrockOreCleanedSeared', item('hbm:bedrock_ore_new:388'))
oreDict.add('bedrockOreCleanedSeared', item('hbm:bedrock_ore_new:389'))

// Sulfuric
oreDict.add('bedrockOreSulfuricWashed', item('hbm:bedrock_ore_new:272'))
oreDict.add('bedrockOreSulfuricWashed', item('hbm:bedrock_ore_new:273'))
oreDict.add('bedrockOreSulfuricWashed', item('hbm:bedrock_ore_new:274'))
oreDict.add('bedrockOreSulfuricWashed', item('hbm:bedrock_ore_new:275'))
oreDict.add('bedrockOreSulfuricWashed', item('hbm:bedrock_ore_new:276'))
oreDict.add('bedrockOreSulfuricWashed', item('hbm:bedrock_ore_new:277'))

// Dissolved
oreDict.add('bedrockOreDissolvedWashed', item('hbm:bedrock_ore_new:336'))
oreDict.add('bedrockOreDissolvedWashed', item('hbm:bedrock_ore_new:337'))
oreDict.add('bedrockOreDissolvedWashed', item('hbm:bedrock_ore_new:338'))
oreDict.add('bedrockOreDissolvedWashed', item('hbm:bedrock_ore_new:339'))
oreDict.add('bedrockOreDissolvedWashed', item('hbm:bedrock_ore_new:340'))
oreDict.add('bedrockOreDissolvedWashed', item('hbm:bedrock_ore_new:341'))

// Cleaned
oreDict.add('bedrockOreCleanedWashed', item('hbm:bedrock_ore_new:400'))
oreDict.add('bedrockOreCleanedWashed', item('hbm:bedrock_ore_new:401'))
oreDict.add('bedrockOreCleanedWashed', item('hbm:bedrock_ore_new:402'))
oreDict.add('bedrockOreCleanedWashed', item('hbm:bedrock_ore_new:403'))
oreDict.add('bedrockOreCleanedWashed', item('hbm:bedrock_ore_new:404'))
oreDict.add('bedrockOreCleanedWashed', item('hbm:bedrock_ore_new:405'))

oreDict.add('anyDrillbit', item('hbm:drillbit:0'))
oreDict.add('anyDrillbit', item('hbm:drillbit:1'))
oreDict.add('anyDrillbit', item('hbm:drillbit:2'))
oreDict.add('anyDrillbit', item('hbm:drillbit:3'))
oreDict.add('anyDrillbit', item('hbm:drillbit:4'))
oreDict.add('anyDrillbit', item('hbm:drillbit:5'))
oreDict.add('anyDrillbit', item('hbm:drillbit:6'))
oreDict.add('anyDrillbit', item('hbm:drillbit:7'))
oreDict.add('anyDrillbit', item('hbm:drillbit:8'))
oreDict.add('anyDrillbit', item('hbm:drillbit:9'))

oreDict.add('anyReinforcedPane', item('hbm:reinforced_glass_pane'))
oreDict.add('anyReinforcedPane', item('hbm:reinforced_laminate_pane'))

oreDict.add('decoBlock', item('hbm:deco_aluminium'))
oreDict.add('decoBlock', item('hbm:deco_titanium'))
oreDict.add('decoBlock', item('hbm:deco_tungsten'))
oreDict.add('decoBlock', item('hbm:deco_steel'))
oreDict.add('decoBlock', item('hbm:deco_rusty_steel'))
oreDict.add('decoBlock', item('hbm:deco_red_copper'))
oreDict.add('decoBlock', item('hbm:deco_lead'))
oreDict.add('decoBlock', item('hbm:deco_beryllium'))


log.info("Loaded ore dictionaries!")

